import json
def status_charging()-> json:
    return {
        'Apparent_output': 98,
        'BackupBuffer': '0',
        'BatteryCharging': True,
        'BatteryDischarging': False,
        'Consumption_Avg': 486,
        'Consumption_W': 403,
        'Fac': 50.05781555175781,
        'FlowConsumptionBattery': False,
        'FlowConsumptionGrid': False,
        'FlowConsumptionProduction': True,
        'FlowGridBattery': False,
        'FlowProductionBattery': True,
        'FlowProductionGrid': True,
        'GridFeedIn_W': 54,
        'IsSystemInstalled': 1,
        'OperatingMode': '2',
        'Pac_total_W': -95,
        'Production_W': 578,
        'RSOC': 98,
        'RemainingCapacity_Wh': 68781,
        'Sac1': 98,
        'Sac2': None,
        'Sac3': None,
        'SystemStatus': 'OnGrid',
        'Timestamp': '2022-04-30 17:00:58',
        'USOC': 98,
        'Uac': 245,
        'Ubat': 212,
        'dischargeNotAllowed': False,
        'generator_autostart': False
    }