import json
def mock_battery()-> json:
    return {
        "balancechargerequest":0.0,
        "chargecurrentlimit":39.97,
        "cyclecount":30.0,
        "dischargecurrentlimit":39.97,
        "fullchargecapacity":201.98,
        "fullchargecapacitywh":20683.490,
        "maximumcelltemperature":19.95,
        "maximumcellvoltage":3.257,
        "maximumcellvoltagenum":0.0,
        "maximummodulecurrent":0.0,
        "maximummoduledcvoltage":104.15,
        "maximummoduletemperature":-273.15,
        "minimumcelltemperature":18.95,
        "minimumcellvoltage":3.251,
        "minimumcellvoltagenum":0.0,
        "minimummodulecurrent":0.0,
        "minimummoduledcvoltage":104.15,
        "minimummoduletemperature":-273.15,
        "nominalmoduledcvoltage":102.4,
        "relativestateofcharge":98.0,
        "remainingcapacity":197.94,
        "systemalarm":0.0,
        "systemcurrent":0.0,
        "systemdcvoltage":208.3,
        "systemstatus":49.0,
        "systemtime":0.0,
        "systemwarning":0.0,
        "usableremainingcapacity":183.80
    }